---

- name: download agent package
  get_url:
    url: "{{ teamcity_agent_server_url_protocol }}://{{ teamcity_agent_server_url }}/update/buildAgent.zip"
    dest: /tmp
    validate_certs: no
    timeout: 60
  register: _teamcity_agent_package

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - zip

- name: create agent build directory
  file:
    path: "{{ teamcity_agent_install_dir }}"
    state: directory
    owner: "{{ teamcity_agent_user }}"
    group: "{{ teamcity_agent_group }}"
    mode: 0755

- name: unpack distribution
  unarchive:
    src: "/tmp/buildAgent.zip"
    dest: "{{ teamcity_agent_install_dir }}"
    owner: "{{ teamcity_agent_user }}"
    group: "{{ teamcity_agent_group }}"
    copy: "no"
  when: _teamcity_agent_package|changed

- name: add TeamCity agent service default configuration
  template:
    src: "teamcity-agent.j2"
    dest: "/etc/default/teamcity-agent"
    mode: 0644

- name: put TeamCity agent service file (sysv)
  template:
    src: "teamcity-agent.conf.j2"
    dest: "/etc/init/teamcity-agent.conf"
    mode: 0644
  when: "ansible_service_mgr != 'systemd'"

- name: put TeamCity agent service file (systemd)
  template:
    src: "teamcity-agent.service.j2"
    dest: "/lib/systemd/system/teamcity-agent.service"
    mode: 0644
  when: "ansible_service_mgr == 'systemd'"

- name: Save agent authorization token
  shell: |
    set -o pipefail
    grep authorizationToken {{ teamcity_agent_install_dir }}/conf/buildAgent.properties | sed 's/authorizationToken=//g'
  changed_when: no
  register: _teamcity_agent_token

- name: add TeamCity agent configuration
  template:
    src: "buildAgent.properties.j2"
    dest: "{{ teamcity_agent_install_dir }}/conf/buildAgent.properties"
    owner: "{{ teamcity_agent_user }}"
    group: "{{ teamcity_agent_group }}"
    mode: 0644

- name: create logging directory
  file:
    path: "{{ teamcity_agent_install_dir }}/logs"
    state: directory
    owner: "{{ teamcity_agent_user }}"
    group: "{{ teamcity_agent_group }}"
    mode: 0755

- name: ensure TeamCity agent is running
  service:
    name: teamcity-agent
    state: started
    enabled: yes
